import { FormEvent, useState } from "react";
import { Eye, EyeOff, KeyRound, ShieldCheck } from "lucide-react";
import { changeAdminCredentials } from "@/lib/api";

export default function AdminSecurity() {
  const [username, setUsername] = useState(""); const [current, setCurrent] = useState("");
  const [newUsername, setNewUsername] = useState(""); const [next, setNext] = useState("");
  const [confirm, setConfirm] = useState(""); const [show, setShow] = useState(false); const [message, setMessage] = useState("");
  const submit = async (event: FormEvent) => { event.preventDefault(); setMessage("");
    if (next !== confirm) return setMessage("New password confirmation does not match.");
    try { await changeAdminCredentials(btoa(`${username.trim().toLowerCase()}:${current}`), current, newUsername.trim().toLowerCase(), next); setMessage("Credentials updated. Use the new username and password next time."); setCurrent(""); setNext(""); setConfirm(""); }
    catch (error) { setMessage(error instanceof Error ? error.message.replace(/^API error \d+: /, "") : "Could not update credentials."); }
  };
  const password = (label: string, value: string, update: (value: string) => void) => <label className="mt-4 block text-sm font-semibold">{label}<span className="relative mt-2 block"><input required type={show ? "text" : "password"} value={value} onChange={(e) => update(e.target.value)} className="h-12 w-full rounded-xl border border-border bg-background px-3 pr-12 outline-none ring-primary focus:ring-2" autoComplete="new-password" /><button type="button" onClick={() => setShow(!show)} aria-label={show ? "Hide passwords" : "Show passwords"} className="absolute right-2 top-2 rounded-lg p-2 text-muted-foreground hover:bg-muted">{show ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}</button></span></label>;
  return <main className="flex flex-1 items-center justify-center px-4 py-16"><form onSubmit={submit} className="w-full max-w-md rounded-[2rem] border border-border bg-card p-8 shadow-xl"><ShieldCheck className="h-10 w-10 text-primary" /><p className="mt-5 text-xs font-semibold uppercase tracking-[0.2em] text-primary">Admin security</p><h1 className="mt-2 font-serif text-3xl font-bold">Change credentials</h1><p className="mt-2 text-sm text-muted-foreground">Update the single administrator username and password.</p>{message && <p role="alert" className="mt-4 rounded-xl bg-muted p-3 text-sm">{message}</p>}<label className="mt-6 block text-sm font-semibold">Current username<input required value={username} onChange={(e) => setUsername(e.target.value)} className="mt-2 h-12 w-full rounded-xl border border-border bg-background px-3 outline-none ring-primary focus:ring-2" autoComplete="username" /></label>{password("Current password", current, setCurrent)}<label className="mt-4 block text-sm font-semibold">New username<input required minLength={3} value={newUsername} onChange={(e) => setNewUsername(e.target.value)} className="mt-2 h-12 w-full rounded-xl border border-border bg-background px-3 outline-none ring-primary focus:ring-2" /></label>{password("New password", next, setNext)}{password("Confirm new password", confirm, setConfirm)}<button className="mt-6 flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-primary font-semibold text-primary-foreground"><KeyRound className="h-4 w-4" />Save credentials</button></form></main>;
}
